import VideoList from "@backoffice/components/VideoList";
import PageContainer from "./PageContainer";

export default function ModerationPage() {
  return (
    <PageContainer className="p-4">
      <div className="flex flex-col">
        <h1>Moderation</h1>
        <p>These videos are generated by users and waiting to be checked for moderation</p>
      </div>
      <VideoList />
    </PageContainer>
  );
}
