---
name: Deploy

on:
  workflow_call: # allow this workflow to be called from other workflows
    secrets:
      OPENAI_API_KEY:
        description: OpenAI token
        required: true
      INFERENCE_KEY:
        description: Inference Key
        required: true
      INFERENCE_CLIENT_ID:
        description: Inference Client ID
        required: true

env:
  ENV: ${{ vars.ENV }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GCP_WORKLOAD_ID: ${{ vars.GCP_WORKLOAD_ID }}
  GCP_WORKLOAD_SA: ${{ vars.GCP_WORKLOAD_SA }}
  GCP_ARTIFACT: ${{ vars.GCP_ARTIFACT }}
  GCP_ARTIFACT_NAME: ${{ vars.GCP_ARTIFACT_NAME }}
  GCP_ARTIFACT_REPO: ${{ vars.GCP_ARTIFACT_REPO }}
  BUCKET_MEDIA: ${{ vars.BUCKET_MEDIA }}
  BUCKET_MUSICDB: ${{ vars.BUCKET_MUSICDB }}
  BUCKET_SOUND: ${{ vars.BUCKET_SOUND }}
  PULUMI_STATE: ${{ vars.PULUMI_STATE }}
  PULUMI_SECRET: ${{ vars.PULUMI_SECRET }}
  INFERENCE_DOMAIN: ${{ vars.INFERENCE_DOMAIN }}
  GIT_REPO: ${{ github.event.repository.name }}
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: ghcr.io/paramaxai/platform:main
    permissions:
      contents: read  # Required to checkout
      id-token: write # Required to get token for GCP
      packages: read  # Required to pull platform image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
          # Check out the current branch instead of the default merge commit on pull_request event
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          secret-openai: ${{ secrets.OPENAI_API_KEY }}
          secret-inference_key: ${{ secrets.INFERENCE_KEY }}
          secret-inference_client_id: ${{ secrets.INFERENCE_CLIENT_ID }}

  stage:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    environment: stage
    container:
      image: ghcr.io/paramaxai/platform:main
    permissions:
      contents: read  # Required to checkout
      id-token: write # Required to get token for GCP
      packages: read  # Required to pull platform image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          secret-openai: ${{ secrets.OPENAI_API_KEY }}
          secret-inference_key: ${{ secrets.INFERENCE_KEY }}
          secret-inference_client_id: ${{ secrets.INFERENCE_CLIENT_ID }}

  prod:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    environment: prod
    container:
      image: ghcr.io/paramaxai/platform:main
    permissions:
      contents: read  # Required to checkout
      id-token: write # Required to get token for GCP
      packages: read  # Required to pull platform image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          secret-openai: ${{ secrets.OPENAI_API_KEY }}
          secret-inference_key: ${{ secrets.INFERENCE_KEY }}
          secret-inference_client_id: ${{ secrets.INFERENCE_CLIENT_ID }}
